management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /-/-
      exposure:
        include: health

server:
  http2:
    enabled: true

app:
  message: Hello
