name: CI

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup bazelisk
      uses: bazelbuild/setup-bazelisk@v2
    -
      name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: |
          "~/.cache/bazel"
          "~/.cache/bazel-repo"
        key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE') }}
        restore-keys: bazel-cache-
    -
      name: Bazel test
      run: bazel test --test_output=errors --test_size_filters=large,enormous //... --config=ci --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }}
